name: proyecto_tierra
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  local_auth: ^2.3.0
  font_awesome_flutter: ^10.7.0
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.2.2
  http: ^1.2.2
  provider: ^6.1.2
  jwt_decoder: ^2.0.1
  onesignal_flutter: ^5.2.9
  shared_preferences: ^2.3.4
  flutter_dotenv: ^5.2.1
  fl_chart: ^0.70.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - .env
